name: nodecommander
description: Network nodes communication. Send commands to nodes and get the responses
homepage: https://github.com/synw/nodecommander
version: 0.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  corsac_jwt: ^0.4.0
  dio: ^3.0.9
  emodebug: ^0.5.0
  err: ^1.0.0
  extra_pedantic: ^1.2.0
  isohttpd: ^0.5.0
  meta: ^1.2.4
  pedantic: ^1.9.2
  prompts: ^1.3.1
  uuid: ^2.0.4
