name: nodecommander
description: A new Flutter project.
version: 0.0.1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  pedantic: ^1.8.0
  extra_pedantic: ^1.1.1+3
  uuid: ^2.0.2
  dio: ^2.1.10
  meta: ^1.1.6
  isohttpd:
    path: ../isohttpd
  prompts: ^1.3.1
